# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a2c21d5c1e5aa71bbbe3f4a080906879e8dfe4e7f25f75c33c1fc727bc621a8f9a7212e059f7bde72eed16521ed762ccff3c69ed7e3769a446901f03edde184

test:
  secret_key_base: 8a461fb2af282d1cfb424922f5aca677a39d70ca0b6c5d4737e8096665675914187b4d3ab78bd6c9d4adb642cac6d68a0f084f90ff5ebbe4e811ed0b64643456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
